version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:16
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:mysql
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: plain
      MYSQL_DATABASE: plaindb
      MYSQL_USER: plainedu
      MYSQL_PASSWORD: plain123
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ../SQL/plaindb.sql:/docker-entrypoint-initdb.d/init.sql:ro
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql-data: